htmlwebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from htmlwebsite import views

app_name='htmlwebsite'

urlpatterns = [

    path('', views.home, name='home'),

    path('signin', views.signin, name='signin'),

    path('vote', views.vote, name='vote'),


]

votingcontact/urls.py
from django.contrib import admin
from django.urls import include, path
from votingcontact import views

urlpatterns = [

    path('', views.home, name='home'),

    
]

votinghome/urls.py
from django.contrib import admin
from django.urls import include, path
from votinghome import views

urlpatterns = [

    path('', views.home, name='home'),

    
]

votingproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('htmlwebsite/', include('htmlwebsite.urls')),
    
]

votingresult/urls.py
from django.contrib import admin
from django.urls import include, path
from votingresult import views

urlpatterns = [

    path('', views.home, name='home'),

    
]

htmlwebsite/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
class poll(models.Model):
    question = models.CharField(max_length=200)
class vote(models.Model):
    poll = models.ForeignKey(poll, on_delete=models.CASCADE)

class Election(models.Model):
    title = models.CharField(max_length=100)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
class Candidate(models.Model):
    name = models.CharField(max_length=100)
    

votingcontact/models.py
from django.db import models

# Create your models here.

votinghome/models.py
from django.db import models

# Create your models here.

votingresult/models.py
from django.db import models

# Create your models here.

htmlwebsite/views.py
from django.shortcuts import redirect, render

# Create your views here.
def home(request):
    return render(request,'index.html')
def signin(request):
    return render(request,'signin.html')
def vote(request):
    return render(request,'vote.html')

votingcontact/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return HttpResponse("This is My Voting Contact Page")

votinghome/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return HttpResponse("This is my Voting Home Page")

votingresult/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return HttpResponse("This is My Voting Result Page")

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>

<body bgcolor="skyblue">
    {%include "navigation.html" %}
    <form>
        <div class="card" style="width: 18rem;">
            <img src="{% static 'vote.jpg' %}" class="card-img-top" alt="My image">

           
            <div class="card-body">
              <h5 class="card-title">Voting</h5>
              <p class="card-text">The Vote is precious</p>
              
                <a class='btn btn-dark' href="{%url 'htmlwebsite:signin' %}">click to vote</a>
                
          </div>
      </form>
    
</body>
</html>

templates/navigation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Voting Application</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
</body>
</html>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voting Results</title>
</head>
<body>
    <h2>Election Results:</h2>
    <ul>
        <li>Candidate A: 100 votes</li>
        <li>Candidate B: 150 votes</li>
        <li>Candidate C: 120 votes</li>
    </ul>
</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"> <!-- Link to the external CSS file -->
    
</head>
<body>
    <form action="your_server_endpoint" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
<br><br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br><br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br><br>

        <button type="submit">
            <a href="{%url 'htmlwebsite:vote' %}">Sign Up</a>
        </button>
    </form>
</body>
</html>

templates/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beautiful Voting Page</title>
    <link rel="stylesheet" href="styles.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <h1>Vote for your favorite option</h1>
        <ul class="options">
            <li class="option">
                <input type="radio" id="option1" name="vote" value="option1">
                <label for="option1">VAMSHI</label>
            </li>
            <li class="option">
                <input type="radio" id="option2" name="vote" value="option2">
                <label for="option2">SHIVASAI</label>
            </li>
            <li class="option">
                <input type="radio" id="option3" name="vote" value="option3">
                <label for="option3">AKHIL</label>
            </li>
        </ul>
        <button type="button" class="btn btn-danger">Vote</button><br><br>


    </div>
</body>
</html>